### ISSUE TITLE
Encode error: don't returning file with unicode chars

### ISSUE THREAD

**Issue by lucasrcezimbra** [Lrcezimbra/ganso-music#8]
Traceback (most recent call last):
  File "/home/lucas/Projects/ganso-music/.venv/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/lucas/Projects/ganso-music/.venv/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 182, in handle_request
    resp.write(item)
  File "/home/lucas/Projects/ganso-music/.venv/lib/python3.5/site-packages/gunicorn/http/wsgi.py", line 342, in write
    self.send_headers()
  File "/home/lucas/Projects/ganso-music/.venv/lib/python3.5/site-packages/gunicorn/http/wsgi.py", line 338, in send_headers
    util.write(self.sock, util.to_bytestring(header_str, "ascii"))
  File "/home/lucas/Projects/ganso-music/.venv/lib/python3.5/site-packages/gunicorn/util.py", line 511, in to_bytestring
    return value.encode(encoding)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 195-196: ordinal not in range(128)

**Comment by lucasrcezimbra** [comment]
566f4ff solves this
